apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xib0855i9-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xib0855i9-go 
  name: xib0855i9-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xib0855i9-go 
